config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My blog</h1>
    <span>
      <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
  <div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Hear some of my thoughts and news about upcoming projects.</p>
    </div>

      <%= source_helper("alert alert-primary blog_sidebar_source") %>
    
    <div class="sidebar-module">
      <h4>Get Social</h4>
      <ol class="list-unstyled social-links">
        <li><a href="https://github.com/kadenjenson" target="_blank"><%= fa_icon "github" %></a></li>
        <li><a href="https://www.linkedin.com/in/kaden1227/" target="_blank"><%= fa_icon "linkedin" %></a></li>
      </ol>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<!-- <nav class="navbar fixed-top navbar-dark bg-dark text">
  <ul class="navbar-nav" id="line-up">
    <li><%= nav_helper 'text-white nav-items', 'li' %></li>
    <li><%= login_helper 'text-white' %></li>
  </ul>
</nav> -->

<nav class="navbar navbar-dark bg-dark fixed-top line-up" id="links">
  <%= nav_helper 'text-white', 'li' %>
  <li><%= login_helper 'text-white' %></li>
</nav>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolios</h1>
      <%= link_to 'Find out more about me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blogs', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>